'use client'

import { useState, useEffect, useCallback } from 'react'
import { Plus, Copy, Trash2, Edit3, Sparkles, Check, X, RefreshCw, Eye, AlertTriangle, Info } from 'lucide-react'
import { ParsingRule, ShipmentData, FIELD_DISPLAY_NAMES } from '@/types'
import { parseExcelWithRule, parseTextWithRule } from '@/utils/ruleEngine'

interface RuleManagerProps {
  rules: ParsingRule[]
  fileType: 'excel' | 'word' | 'pdf'
  parsedData: {
    type: 'excel' | 'word' | 'pdf'
    sheets?: { name: string; data: string[][] }[]
    lines?: string[]
  } | null
  onRuleSelect: (rule: ParsingRule) => void
  onNewRule: (rule: ParsingRule) => void
  onRefresh: () => void
}

export function RuleManager({ rules, fileType, parsedData, onRuleSelect, onNewRule, onRefresh }: RuleManagerProps) {
  const [showNewRuleModal, setShowNewRuleModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [selectedRuleForEdit, setSelectedRuleForEdit] = useState<ParsingRule | null>(null)
  const [aiGenerating, setAiGenerating] = useState(false)
  const [aiRule, setAiRule] = useState<ParsingRule | null>(null)
  const [aiMetadata, setAiMetadata] = useState<Record<string, { status: string; reason: string }>>({})
  const [copiedRuleId, setCopiedRuleId] = useState<string | null>(null)
  const [showPreviewModal, setShowPreviewModal] = useState(false)
  const [previewData, setPreviewData] = useState<ShipmentData[]>([])
  const [previewing, setPreviewing] = useState(false)
  const [previewError, setPreviewError] = useState<string | null>(null)

  const handleGenerateRule = useCallback(async () => {
    if (!parsedData) return

    setAiGenerating(true)
    setAiRule(null)
    setAiMetadata({})

    try {
      const response = await fetch('/api/generate-rule', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(parsedData),
      })

      const result = await response.json()

      if (result.error) {
        console.error('Failed to generate rule:', result.error)
        return
      }

      setAiRule(result.rule)
      setAiMetadata(result.ai_metadata || {})
    } catch (error) {
      console.error('Failed to call AI:', error)
    } finally {
      setAiGenerating(false)
    }
  }, [parsedData])

  // 当规则列表为空且有解析数据时，自动打开新建规则弹窗并触发 AI 生成
  const [autoTriggered, setAutoTriggered] = useState(false)
  useEffect(() => {
    if (rules.length === 0 && parsedData && !autoTriggered && !showNewRuleModal) {
      setShowNewRuleModal(true)
      setAutoTriggered(true)
    }
  }, [rules.length, parsedData, autoTriggered, showNewRuleModal])

  // 当弹窗打开且没有 AI 结果时，自动触发
  const [autoGenerated, setAutoGenerated] = useState(false)
  useEffect(() => {
    if (showNewRuleModal && !aiRule && !aiGenerating && rules.length === 0 && !autoGenerated) {
      setAutoGenerated(true)
      handleGenerateRule()
    }
  }, [showNewRuleModal, aiRule, aiGenerating, rules.length, autoGenerated, handleGenerateRule])

  const handleSaveRule = async (rule: ParsingRule) => {
    try {
      const response = await fetch('/api/rules', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(rule),
      })

      const result = await response.json()
      if (result.success) {
        onRefresh()
      }
    } catch (error) {
      console.error('Failed to save rule:', error)
    }
  }

  const handleDeleteRule = async (ruleName: string) => {
    if (!confirm(`确定要删除规则 "${ruleName}" 吗？`)) return

    try {
      const response = await fetch(`/api/rules?name=${encodeURIComponent(ruleName)}`, {
        method: 'DELETE',
      })

      const result = await response.json()
      if (result.success) {
        onRefresh()
      }
    } catch (error) {
      console.error('Failed to delete rule:', error)
    }
  }

  const handleCopyRule = (rule: ParsingRule) => {
    const copiedRule: ParsingRule = {
      ...rule,
      id: undefined,
      name: `${rule.name} (副本)`,
      description: rule.description ? `${rule.description} (复制)` : undefined,
    }
    setSelectedRuleForEdit(copiedRule)
    setShowEditModal(true)
    setCopiedRuleId(rule.id || rule.name)
    setTimeout(() => setCopiedRuleId(null), 2000)
  }

  const handleApplyRule = (rule: ParsingRule) => {
    onRuleSelect(rule)
    setShowNewRuleModal(false)
    setShowEditModal(false)
  }

  const handleTestParse = (rule: ParsingRule) => {
    if (!parsedData) {
      setPreviewError('没有可用的样例数据，请先上传文件')
      setPreviewData([])
      setShowPreviewModal(true)
      return
    }

    setPreviewing(true)
    setPreviewError(null)
    setPreviewData([])

    try {
      let results: ShipmentData[]
      if (rule.file_type === 'excel') {
        if (!parsedData.sheets) {
          setPreviewError('Excel 数据为空')
          setShowPreviewModal(true)
          setPreviewing(false)
          return
        }
        results = parseExcelWithRule(parsedData.sheets, rule)
      } else {
        // word or pdf
        if (!parsedData.lines) {
          setPreviewError('文本数据为空')
          setShowPreviewModal(true)
          setPreviewing(false)
          return
        }
        results = parseTextWithRule(parsedData.lines, rule)
      }

      // 只显示前 20 行预览
      setPreviewData(results.slice(0, 20))
      if (results.length === 0) {
        setPreviewError('解析结果为空，请检查规则配置')
      }
    } catch (error: any) {
      setPreviewError(`解析出错: ${error?.message || '未知错误'}`)
    } finally {
      setPreviewing(false)
      setShowPreviewModal(true)
    }
  }

  const filteredRules = rules.filter(r => r.file_type === fileType)

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-[#1d2129]">选择解析规则</h2>
          <p className="text-sm text-[#86909c] mt-1">
            当前文件类型：{fileType === 'excel' ? 'Excel' : fileType === 'word' ? 'Word' : 'PDF'}
          </p>
        </div>
        <button
          onClick={() => setShowNewRuleModal(true)}
          className="jt-btn-primary flex items-center gap-2 px-4 py-2"
        >
          <Plus className="w-5 h-5" />
          新建规则
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredRules.length === 0 ? (
          <div className="col-span-full p-12 text-center bg-white rounded-xl border border-dashed border-[#d0e8e8]">
            <div className="w-16 h-16 mx-auto mb-4 bg-[#e8fafa] rounded-full flex items-center justify-center">
              <Edit3 className="w-8 h-8 text-[#0fc6c2]" />
            </div>
            <p className="text-[#86909c] mb-4">暂无匹配的解析规则</p>
            <button
              onClick={() => setShowNewRuleModal(true)}
              className="jt-btn-primary px-6 py-2"
            >
              创建新规则
            </button>
          </div>
        ) : (
          filteredRules.map((rule) => (
            <div
              key={rule.id || rule.name}
              className="jt-card p-5 cursor-pointer hover:border-[#0fc6c2] group"
              onClick={() => onRuleSelect(rule)}
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-2">
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                    rule.structure_type === 'standard' ? 'bg-blue-100 text-blue-700' :
                    rule.structure_type === 'matrix' ? 'bg-purple-100 text-purple-700' :
                    rule.structure_type === 'card' ? 'bg-orange-100 text-orange-700' :
                    'bg-green-100 text-green-700'
                  }`}>
                    {rule.structure_type === 'standard' && '标准'}
                    {rule.structure_type === 'matrix' && '矩阵'}
                    {rule.structure_type === 'card' && '卡片'}
                    {rule.structure_type === 'free_text' && '文本'}
                  </span>
                </div>
                <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button
                    onClick={(e) => { e.stopPropagation(); handleCopyRule(rule) }}
                    className="p-1.5 text-gray-400 hover:text-[#0fc6c2] hover:bg-[#e8fafa] rounded transition-colors"
                    title="复制规则"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                  <button
                    onClick={(e) => { e.stopPropagation(); setSelectedRuleForEdit(rule); setShowEditModal(true) }}
                    className="p-1.5 text-gray-400 hover:text-[#0fc6c2] hover:bg-[#e8fafa] rounded transition-colors"
                    title="编辑规则"
                  >
                    <Edit3 className="w-4 h-4" />
                  </button>
                  <button
                    onClick={(e) => { e.stopPropagation(); handleDeleteRule(rule.name) }}
                    className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors"
                    title="删除规则"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
              
              <h3 className="font-semibold text-[#1d2129] mb-2">{rule.name}</h3>
              {rule.description && (
                <p className="text-sm text-[#86909c] line-clamp-2">{rule.description}</p>
              )}
              
              <div className="mt-4 pt-4 border-t border-gray-100">
                <div className="flex items-center justify-between text-xs text-[#86909c]">
                  <span>{rule.file_type.toUpperCase()} 文件</span>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={(e) => { e.stopPropagation(); handleTestParse(rule) }}
                      className="p-1 text-[#86909c] hover:text-blue-500 hover:bg-blue-50 rounded transition-colors"
                      title="试解析"
                    >
                      <Eye className="w-4 h-4" />
                    </button>
                    <span>点击使用</span>
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      {showNewRuleModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-full max-w-3xl mx-4 max-h-[90vh] overflow-hidden flex flex-col">
            <div className="flex items-center justify-between mb-6">
              <div>
                <h3 className="text-xl font-bold text-[#1d2129]">新建解析规则</h3>
                <p className="text-sm text-[#86909c] mt-1">
                  AI 将自动分析文件结构并生成推荐规则
                </p>
              </div>
              <button
                onClick={() => { setShowNewRuleModal(false); setAiRule(null); setAiMetadata({}) }}
                className="p-2 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto">
              <div className="mb-6">
                <button
                  onClick={handleGenerateRule}
                  disabled={aiGenerating}
                  className="w-full jt-btn-primary flex items-center justify-center gap-2 py-3"
                >
                  {aiGenerating ? (
                    <>
                      <RefreshCw className="w-5 h-5 animate-spin" />
                      AI 分析中...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-5 h-5" />
                      智能分析文件并生成规则
                    </>
                  )}
                </button>
              </div>

              {aiRule && (
                <div className="space-y-4">
                  <div className="p-4 bg-[#e8fafa] rounded-xl border border-[#d0e8e8]">
                    <div className="flex items-center gap-2 mb-2">
                      <Check className="w-5 h-5 text-[#0fc6c2]" />
                      <span className="font-medium text-[#0b6e6e]">AI 已生成推荐规则</span>
                    </div>
                    <p className="text-sm text-[#0b6e6e]">
                      {Object.keys(aiMetadata).length > 0 
                        ? '以下字段映射由 AI 分析得出，点击确认后可使用或进一步编辑'
                        : '规则已生成，可直接使用或进一步编辑'}
                    </p>
                  </div>

                  <div className="p-4 bg-gray-50 rounded-xl">
                    <div className="flex items-center gap-2 mb-3">
                      <span className="font-medium text-gray-800">规则名称</span>
                      <input
                        type="text"
                        value={aiRule.name}
                        onChange={(e) => setAiRule({ ...aiRule, name: e.target.value })}
                        className="flex-1 px-3 py-1 border border-gray-200 rounded-lg text-sm"
                      />
                    </div>
                    
                    <div className="mb-3">
                      <span className="font-medium text-gray-800 block mb-2">结构类型</span>
                      <select
                        value={aiRule.structure_type}
                        onChange={(e) => setAiRule({ ...aiRule, structure_type: e.target.value as ParsingRule['structure_type'] })}
                        className="w-full px-3 py-2 border border-gray-200 rounded-lg"
                      >
                        <option value="standard">标准表格</option>
                        <option value="matrix">矩阵转置</option>
                        <option value="card">卡片式</option>
                        <option value="free_text">纯文本</option>
                      </select>
                    </div>

                    {aiMetadata && Object.keys(aiMetadata).length > 0 && (
                      <div className="mt-4">
                        <h4 className="text-sm font-medium text-gray-700 mb-2">AI 字段识别结果</h4>
                        <div className="space-y-2">
                          {Object.entries(aiMetadata).map(([field, info]) => (
                            <div key={field} className={`flex items-center justify-between p-2 rounded-lg ${
                              info.status === 'confident' ? 'bg-green-50' :
                              info.status === 'guessed' ? 'bg-yellow-50' : 'bg-gray-50'
                            }`}>
                              <span className="text-sm text-gray-700">{field}</span>
                              <span className={`text-xs px-2 py-0.5 rounded-full ${
                                info.status === 'confident' ? 'bg-green-100 text-green-700' :
                                info.status === 'guessed' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-700'
                              }`}>
                                {info.status === 'confident' ? '确定' : info.status === 'guessed' ? '推测' : '未找到'}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    <div className="flex gap-3 mt-4">
                      <button
                        onClick={() => handleTestParse(aiRule)}
                        className="flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 transition-colors"
                      >
                        <Eye className="w-4 h-4" />
                        试解析
                      </button>
                      <button
                        onClick={() => handleApplyRule(aiRule)}
                        className="flex-1 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
                      >
                        使用此规则解析
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {!aiRule && !aiGenerating && (
                <div className="text-center py-12">
                  <div className="w-20 h-20 mx-auto mb-4 bg-gray-100 rounded-full flex items-center justify-center">
                    <Sparkles className="w-10 h-10 text-gray-400" />
                  </div>
                  <p className="text-gray-500 mb-4">点击上方按钮，AI 将自动分析您上传的文件</p>
                  <p className="text-sm text-gray-400">
                    AI 将识别文件结构、字段位置，并生成一套解析规则供您使用
                  </p>
                </div>
              )}
            </div>

            <div className="mt-6 pt-4 border-t border-gray-200 flex justify-end gap-3">
              <button
                onClick={() => { setShowNewRuleModal(false); setAiRule(null); setAiMetadata({}) }}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
              >
                取消
              </button>
              {aiRule && (
                <>
                  <button
                    onClick={() => { handleSaveRule(aiRule); setShowNewRuleModal(false); setAiRule(null); setAiMetadata({}) }}
                    className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
                  >
                    保存规则
                  </button>
                  <button
                    onClick={() => handleApplyRule(aiRule)}
                    className="jt-btn-primary px-4 py-2"
                  >
                    使用此规则解析
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {showEditModal && selectedRuleForEdit && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-full max-w-3xl mx-4 max-h-[90vh] overflow-hidden flex flex-col">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-[#1d2129]">编辑解析规则</h3>
              <button
                onClick={() => { setShowEditModal(false); setSelectedRuleForEdit(null) }}
                className="p-2 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">规则名称</label>
                <input
                  type="text"
                  value={selectedRuleForEdit.name}
                  onChange={(e) => setSelectedRuleForEdit({ ...selectedRuleForEdit, name: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#0fc6c2] focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">描述</label>
                <textarea
                  value={selectedRuleForEdit.description || ''}
                  onChange={(e) => setSelectedRuleForEdit({ ...selectedRuleForEdit, description: e.target.value })}
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#0fc6c2] focus:border-transparent"
                  placeholder="描述此规则适用的文件特征..."
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">文件类型</label>
                <select
                  value={selectedRuleForEdit.file_type}
                  onChange={(e) => setSelectedRuleForEdit({ ...selectedRuleForEdit, file_type: e.target.value as ParsingRule['file_type'] })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#0fc6c2] focus:border-transparent"
                >
                  <option value="excel">Excel</option>
                  <option value="word">Word</option>
                  <option value="pdf">PDF</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">结构类型</label>
                <select
                  value={selectedRuleForEdit.structure_type}
                  onChange={(e) => setSelectedRuleForEdit({ ...selectedRuleForEdit, structure_type: e.target.value as ParsingRule['structure_type'] })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#0fc6c2] focus:border-transparent"
                >
                  <option value="standard">标准表格</option>
                  <option value="matrix">矩阵转置</option>
                  <option value="card">卡片式</option>
                  <option value="free_text">纯文本</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">规则配置（JSON）</label>
                <textarea
                  value={JSON.stringify(selectedRuleForEdit.config, null, 2)}
                  onChange={(e) => {
                    try {
                      const config = JSON.parse(e.target.value)
                      setSelectedRuleForEdit({ ...selectedRuleForEdit, config })
                    } catch {
                      // Invalid JSON, keep previous value
                    }
                  }}
                  rows={10}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#0fc6c2] focus:border-transparent font-mono text-sm"
                />
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-gray-200 flex justify-end gap-3">
              <button
                onClick={() => { setShowEditModal(false); setSelectedRuleForEdit(null) }}
                className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
              >
                取消
              </button>
              <button
                onClick={() => handleTestParse(selectedRuleForEdit)}
                className="flex items-center gap-2 px-4 py-2 bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 transition-colors"
              >
                <Eye className="w-4 h-4" />
                试解析
              </button>
              <button
                onClick={() => { handleSaveRule(selectedRuleForEdit); setShowEditModal(false); setSelectedRuleForEdit(null) }}
                className="jt-btn-primary px-4 py-2"
              >
                保存修改
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 试解析预览弹窗 */}
      {showPreviewModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-full max-w-5xl mx-4 max-h-[90vh] overflow-hidden flex flex-col">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Eye className="w-5 h-5 text-blue-600" />
                <h3 className="text-xl font-bold text-[#1d2129]">试解析预览</h3>
              </div>
              <button
                onClick={() => { setShowPreviewModal(false); setPreviewError(null) }}
                className="p-2 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto">
              {previewing && (
                <div className="flex items-center justify-center py-12">
                  <RefreshCw className="w-8 h-8 text-[#0fc6c2] animate-spin" />
                  <span className="ml-3 text-gray-600">正在解析...</span>
                </div>
              )}

              {previewError && !previewing && (
                <div className="p-4 bg-red-50 rounded-xl border border-red-200">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="w-5 h-5 text-red-500" />
                    <span className="font-medium text-red-700">{previewError}</span>
                  </div>
                </div>
              )}

              {previewData.length > 0 && !previewing && (
                <div>
                  <div className="flex items-center gap-2 mb-3 p-3 bg-blue-50 rounded-lg">
                    <Info className="w-4 h-4 text-blue-600" />
                    <span className="text-sm text-blue-700">
                      解析成功！共 {previewData.length} 条记录
                      {previewData.length === 20 && '（仅显示前 20 条）'}
                    </span>
                  </div>

                  <div className="overflow-x-auto rounded-lg border border-gray-200">
                    <table className="min-w-full divide-y divide-gray-200">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">#</th>
                          {Object.keys(previewData[0] || {})
                            .filter(key => key !== 'id' && key !== 'created_at' && previewData[0]?.[key as keyof ShipmentData] !== undefined)
                            .map((key) => (
                              <th key={key} className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider whitespace-nowrap">
                                {FIELD_DISPLAY_NAMES[key] || key}
                              </th>
                            ))}
                        </tr>
                      </thead>
                      <tbody className="bg-white divide-y divide-gray-200">
                        {previewData.map((row, idx) => (
                          <tr key={idx} className="hover:bg-gray-50">
                            <td className="px-3 py-2 text-sm text-gray-500">{idx + 1}</td>
                            {Object.keys(row).filter(key => key !== 'id' && key !== 'created_at').map((key) => (
                              <td key={key} className="px-3 py-2 text-sm text-gray-700 whitespace-nowrap max-w-[200px] truncate" title={String(row[key as keyof ShipmentData] ?? '')}>
                                {String(row[key as keyof ShipmentData] ?? '-')}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}