'use client'

import { useCallback, useEffect, useState } from 'react'
import {
  AlertTriangle,
  Check,
  Copy,
  Edit3,
  Eye,
  Info,
  Plus,
  RefreshCw,
  Sparkles,
  Trash2,
  X,
} from 'lucide-react'
import { FIELD_DISPLAY_NAMES, ParsingRule, ShipmentData } from '@/types'
import { RuleConfigForm } from '@/components/RuleConfigForm'
import { parseExcelWithRule, parseTextWithRule } from '@/utils/ruleEngine'
import { FILE_TYPE_LABELS, STRUCTURE_TYPE_LABELS, normalizeRuleConfig } from '@/utils/ruleConfig'

interface RuleManagerProps {
  rules: ParsingRule[]
  fileType: 'excel' | 'word' | 'pdf'
  parsedData: {
    type: 'excel' | 'word' | 'pdf'
    fileName?: string
    sheets?: { name: string; data: string[][] }[]
    lines?: string[]
  } | null
  onRuleSelect: (rule: ParsingRule) => void
  onNewRule: (rule: ParsingRule) => void
  onRefresh: () => void
}

const AI_STATUS_LABELS: Record<string, string> = {
  confident: '确定',
  guessed: '推测',
  not_found: '未找到',
}

export function RuleManager({ rules, fileType, parsedData, onRuleSelect, onRefresh }: RuleManagerProps) {
  const [showNewRuleModal, setShowNewRuleModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [selectedRuleForEdit, setSelectedRuleForEdit] = useState<ParsingRule | null>(null)
  const [aiGenerating, setAiGenerating] = useState(false)
  const [aiRule, setAiRule] = useState<ParsingRule | null>(null)
  const [aiMetadata, setAiMetadata] = useState<Record<string, { status: string; reason: string }>>({})
  const [aiError, setAiError] = useState<string | null>(null)
  const [aiWarning, setAiWarning] = useState<string | null>(null)
  const [aiConfigError, setAiConfigError] = useState<string | null>(null)
  const [copiedRuleId, setCopiedRuleId] = useState<string | null>(null)
  const [showPreviewModal, setShowPreviewModal] = useState(false)
  const [previewData, setPreviewData] = useState<ShipmentData[]>([])
  const [previewing, setPreviewing] = useState(false)
  const [previewError, setPreviewError] = useState<string | null>(null)
  const [autoTriggered, setAutoTriggered] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false)

  const filteredRules = rules.filter(rule => rule.file_type === fileType)

  const handleGenerateRule = useCallback(async () => {
    if (!parsedData) {
      setAiError('没有可分析的文件结构，请先上传文件')
      return
    }

    setAiGenerating(true)
    setAiRule(null)
    setAiMetadata({})
    setAiError(null)
    setAiWarning(null)
    setAiConfigError(null)

    try {
      const response = await fetch('/api/generate-rule', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(parsedData),
      })
      const result = await response.json()

      if (!response.ok || result.error) {
        setAiError(result.error || `规则生成接口异常：HTTP ${response.status}`)
        return
      }

      if (!result.rule) {
        setAiError('规则生成失败：接口没有返回规则内容')
        return
      }

      const generatedRule: ParsingRule = {
        ...(result.rule as ParsingRule),
        file_type: fileType,
        config: normalizeRuleConfig((result.rule as ParsingRule).config),
      }
      setAiRule(generatedRule)
      setAiMetadata(result.ai_metadata || {})
      setAiWarning(result.warning || null)
    } catch (error) {
      setAiError(error instanceof Error ? error.message : 'AI 规则生成请求失败')
    } finally {
      setAiGenerating(false)
    }
  }, [fileType, parsedData])

  useEffect(() => {
    if (rules.length === 0 && parsedData && !autoTriggered && !showNewRuleModal) {
      setShowNewRuleModal(true)
      setAutoTriggered(true)
    }
  }, [rules.length, parsedData, autoTriggered, showNewRuleModal])

  useEffect(() => {
    if (showNewRuleModal && !aiRule && !aiGenerating && rules.length === 0 && !autoGenerated) {
      setAutoGenerated(true)
      handleGenerateRule()
    }
  }, [showNewRuleModal, aiRule, aiGenerating, rules.length, autoGenerated, handleGenerateRule])

  const handleSaveRule = async (rule: ParsingRule) => {
    const normalizedRule = { ...rule, config: normalizeRuleConfig(rule.config) }
    try {
      const response = await fetch('/api/rules', {
        method: normalizedRule.id ? 'PUT' : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(normalizedRule),
      })
      const result = await response.json()
      if (response.ok && result.success) {
        onRefresh()
      }
    } catch (error) {
      console.error('Failed to save rule:', error)
    }
  }

  const handleDeleteRule = async (ruleName: string) => {
    if (!confirm(`确定要删除规则 "${ruleName}" 吗？`)) return

    try {
      const response = await fetch(`/api/rules?name=${encodeURIComponent(ruleName)}`, {
        method: 'DELETE',
      })
      const result = await response.json()
      if (response.ok && result.success) {
        onRefresh()
      }
    } catch (error) {
      console.error('Failed to delete rule:', error)
    }
  }

  const handleCopyRule = (rule: ParsingRule) => {
    const copiedRule: ParsingRule = {
      ...rule,
      id: undefined,
      name: `${rule.name}（副本）`,
      description: rule.description ? `${rule.description}（复制）` : undefined,
      config: normalizeRuleConfig(rule.config),
    }
    setSelectedRuleForEdit(copiedRule)
    setShowEditModal(true)
    setCopiedRuleId(rule.id || rule.name)
    setTimeout(() => setCopiedRuleId(null), 2000)
  }

  const parseWithRule = (rule: ParsingRule) => {
    const normalizedRule = { ...rule, config: normalizeRuleConfig(rule.config) }

    if (!parsedData) {
      throw new Error('没有可用的样例数据，请先上传文件')
    }

    if (normalizedRule.file_type === 'excel') {
      if (!parsedData.sheets) throw new Error('Excel 数据为空')
      return parseExcelWithRule(parsedData.sheets, normalizedRule)
    }

    if (!parsedData.lines) throw new Error('文本数据为空')
    return parseTextWithRule(parsedData.lines, normalizedRule)
  }

  const handleApplyRule = (rule: ParsingRule) => {
    if (aiConfigError) return

    const normalizedRule = { ...rule, config: normalizeRuleConfig(rule.config) }

    try {
      const results = parseWithRule(normalizedRule)
      if (results.length === 0) {
        setAiError('规则没有解析出任何数据，请先点击“试解析”查看原因，或调整上方规则表单')
        return
      }
    } catch (error) {
      setAiError(`规则预检失败：${error instanceof Error ? error.message : '未知错误'}`)
      return
    }

    onRuleSelect(normalizedRule)
    setShowNewRuleModal(false)
    setShowEditModal(false)
    setAiError(null)
    setAiWarning(null)
    setAiConfigError(null)
  }

  const closeNewRuleModal = () => {
    setShowNewRuleModal(false)
    setAiRule(null)
    setAiMetadata({})
    setAiError(null)
    setAiWarning(null)
    setAiConfigError(null)
  }

  const handleTestParse = (rule: ParsingRule) => {
    setPreviewing(true)
    setPreviewError(null)
    setPreviewData([])
    setShowPreviewModal(true)

    try {
      const results = parseWithRule(rule)
      setPreviewData(results.slice(0, 20))
      if (results.length === 0) {
        setPreviewError('解析结果为空，请检查规则配置')
      }
    } catch (error) {
      setPreviewError(`解析出错: ${error instanceof Error ? error.message : '未知错误'}`)
    } finally {
      setPreviewing(false)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-[#1d2129]">选择解析规则</h2>
          <p className="mt-1 text-sm text-[#86909c]">
            当前文件类型：{FILE_TYPE_LABELS[fileType]}
          </p>
        </div>
        <button
          onClick={() => setShowNewRuleModal(true)}
          className="jt-btn-primary flex items-center gap-2 px-4 py-2"
        >
          <Plus className="h-5 w-5" />
          新建规则
        </button>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        {filteredRules.length === 0 ? (
          <div className="col-span-full rounded-xl border border-dashed border-[#d0e8e8] bg-white p-12 text-center">
            <Sparkles className="mx-auto mb-4 h-12 w-12 text-[#0fc6c2]" />
            <p className="mb-2 text-gray-600">暂无可用规则</p>
            <p className="text-sm text-gray-400">点击新建规则，可让 AI 根据样本生成初始规则。</p>
          </div>
        ) : (
          filteredRules.map((rule) => (
            <div key={rule.id || rule.name} className="rounded-xl border border-gray-200 bg-white p-5 transition-shadow hover:shadow-md">
              <div className="mb-3 flex items-start justify-between">
                <div className="flex flex-wrap gap-2">
                  <span className="rounded-full bg-[#e8fafa] px-2 py-1 text-xs font-medium text-[#0b6e6e]">
                    {STRUCTURE_TYPE_LABELS[rule.structure_type]}
                  </span>
                  <span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-medium text-gray-600">
                    {FILE_TYPE_LABELS[rule.file_type]}
                  </span>
                </div>
                <div className="flex gap-1">
                  <button
                    onClick={() => handleCopyRule(rule)}
                    className="rounded p-1.5 text-gray-400 hover:bg-[#e8fafa] hover:text-[#0fc6c2]"
                    title="复制规则"
                  >
                    {copiedRuleId === (rule.id || rule.name) ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  </button>
                  <button
                    onClick={() => {
                      setSelectedRuleForEdit({ ...rule, config: normalizeRuleConfig(rule.config) })
                      setShowEditModal(true)
                    }}
                    className="rounded p-1.5 text-gray-400 hover:bg-[#e8fafa] hover:text-[#0fc6c2]"
                    title="编辑规则"
                  >
                    <Edit3 className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => handleDeleteRule(rule.name)}
                    className="rounded p-1.5 text-gray-400 hover:bg-red-50 hover:text-red-500"
                    title="删除规则"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>

              <h3 className="mb-2 font-semibold text-[#1d2129]">{rule.name}</h3>
              {rule.description && (
                <p className="mb-4 line-clamp-2 text-sm text-gray-500">{rule.description}</p>
              )}
              <button
                onClick={() => onRuleSelect({ ...rule, config: normalizeRuleConfig(rule.config) })}
                className="w-full rounded-lg bg-[#e8fafa] px-4 py-2 text-sm font-medium text-[#0b6e6e] transition-colors hover:bg-[#d5f5f5]"
              >
                使用此规则解析
              </button>
            </div>
          ))
        )}
      </div>

      {showNewRuleModal && (
        <AiRuleModal
          aiRule={aiRule}
          aiMetadata={aiMetadata}
          aiError={aiError}
          aiWarning={aiWarning}
          aiGenerating={aiGenerating}
          aiConfigError={aiConfigError}
          onGenerate={handleGenerateRule}
          onRuleChange={setAiRule}
          onConfigErrorChange={setAiConfigError}
          onCancel={closeNewRuleModal}
          onSave={() => {
            if (!aiRule || aiConfigError) return
            handleSaveRule(aiRule)
            closeNewRuleModal()
          }}
          onApply={() => aiRule && handleApplyRule(aiRule)}
          onTest={() => aiRule && handleTestParse(aiRule)}
        />
      )}

      {showEditModal && selectedRuleForEdit && (
        <EditRuleModal
          rule={selectedRuleForEdit}
          onChange={setSelectedRuleForEdit}
          onCancel={() => {
            setShowEditModal(false)
            setSelectedRuleForEdit(null)
          }}
          onTest={() => handleTestParse(selectedRuleForEdit)}
          onSave={() => {
            handleSaveRule(selectedRuleForEdit)
            setShowEditModal(false)
            setSelectedRuleForEdit(null)
          }}
        />
      )}

      {showPreviewModal && (
        <PreviewModal
          previewing={previewing}
          previewError={previewError}
          previewData={previewData}
          onClose={() => {
            setShowPreviewModal(false)
            setPreviewError(null)
          }}
        />
      )}
    </div>
  )
}

function AiRuleModal({
  aiRule,
  aiMetadata,
  aiError,
  aiWarning,
  aiGenerating,
  aiConfigError,
  onGenerate,
  onRuleChange,
  onConfigErrorChange,
  onCancel,
  onSave,
  onApply,
  onTest,
}: {
  aiRule: ParsingRule | null
  aiMetadata: Record<string, { status: string; reason: string }>
  aiError: string | null
  aiWarning: string | null
  aiGenerating: boolean
  aiConfigError: string | null
  onGenerate: () => void
  onRuleChange: (rule: ParsingRule) => void
  onConfigErrorChange: (message: string | null) => void
  onCancel: () => void
  onSave: () => void
  onApply: () => void
  onTest: () => void
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-3 md:p-6">
      <div className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-gray-100 px-6 py-4">
          <h3 className="text-xl font-bold text-[#1d2129]">AI 辅助生成规则</h3>
          <button onClick={onCancel} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-5">
          <button
            onClick={onGenerate}
            disabled={aiGenerating}
            className="jt-btn-primary mb-4 flex w-full items-center justify-center gap-2 py-3 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {aiGenerating ? <RefreshCw className="h-5 w-5 animate-spin" /> : <Sparkles className="h-5 w-5" />}
            {aiGenerating ? 'AI 分析中...' : '智能分析文件并生成规则'}
          </button>

          {aiError && (
            <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
              {aiError}
            </div>
          )}

          {aiWarning && !aiError && (
            <div className="mb-4 rounded-xl border border-yellow-200 bg-yellow-50 p-4 text-sm text-yellow-700">
              {aiWarning}
            </div>
          )}

          {aiRule ? (
            <div className="space-y-4">
              <div className="rounded-xl border border-[#d0e8e8] bg-[#e8fafa] p-4">
                <div className="mb-2 flex items-center gap-2">
                  <Check className="h-5 w-5 text-[#0fc6c2]" />
                  <span className="font-medium text-[#0b6e6e]">AI 已生成推荐规则</span>
                </div>
                <p className="text-sm text-[#0b6e6e]">可以先微调表单，再试解析或使用规则。</p>
              </div>

              <div className="rounded-xl bg-gray-50 p-4">
                <div className="mb-3">
                  <label className="mb-2 block text-sm font-medium text-gray-800">规则名称</label>
                  <input
                    type="text"
                    value={aiRule.name}
                    onChange={(event) => onRuleChange({ ...aiRule, name: event.target.value })}
                    className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
                  />
                </div>
                <div className="mb-3">
                  <label className="mb-2 block text-sm font-medium text-gray-800">规则描述</label>
                  <textarea
                    value={aiRule.description || ''}
                    onChange={(event) => onRuleChange({ ...aiRule, description: event.target.value })}
                    rows={2}
                    className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
                    placeholder="说明这个规则适用的客户、仓库或文件模板"
                  />
                </div>
                <div className="mb-4 grid gap-3 md:grid-cols-2">
                  <label className="text-sm text-gray-700">
                    结构类型
                    <select
                      value={aiRule.structure_type}
                      onChange={(event) => onRuleChange({ ...aiRule, structure_type: event.target.value as ParsingRule['structure_type'] })}
                      className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
                    >
                      {Object.entries(STRUCTURE_TYPE_LABELS).map(([value, label]) => (
                        <option key={value} value={value}>{label}</option>
                      ))}
                    </select>
                  </label>
                  <label className="text-sm text-gray-700">
                    文件类型
                    <select
                      value={aiRule.file_type}
                      onChange={(event) => onRuleChange({ ...aiRule, file_type: event.target.value as ParsingRule['file_type'] })}
                      className="mt-1 w-full rounded-lg border border-gray-200 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
                    >
                      {Object.entries(FILE_TYPE_LABELS).map(([value, label]) => (
                        <option key={value} value={value}>{label}</option>
                      ))}
                    </select>
                  </label>
                </div>

                {Object.keys(aiMetadata).length > 0 && (
                  <div className="mb-4">
                    <h4 className="mb-2 text-sm font-medium text-gray-700">AI 字段识别结果</h4>
                    <div className="grid gap-2 md:grid-cols-2">
                      {Object.entries(aiMetadata).map(([field, info]) => (
                        <div
                          key={field}
                          className={`flex items-center justify-between rounded-lg p-2 ${
                            info.status === 'confident'
                              ? 'bg-green-50'
                              : info.status === 'guessed'
                                ? 'bg-yellow-50'
                                : 'bg-gray-50'
                          }`}
                        >
                          <span className="text-sm text-gray-700">{FIELD_DISPLAY_NAMES[field] || field}</span>
                          <span className="rounded-full bg-white px-2 py-0.5 text-xs text-gray-600">
                            {AI_STATUS_LABELS[info.status] || info.status}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <RuleConfigForm
                  rule={aiRule}
                  onChange={(config) => {
                    onRuleChange({ ...aiRule, config: normalizeRuleConfig(config) })
                    onConfigErrorChange(null)
                  }}
                  onValidityChange={(valid, message) => onConfigErrorChange(valid ? null : (message || '规则配置格式不正确'))}
                />
              </div>
            </div>
          ) : (
            !aiGenerating && (
              <div className="py-12 text-center">
                <Sparkles className="mx-auto mb-4 h-12 w-12 text-gray-300" />
                <p className="text-gray-500">点击上方按钮，AI 将自动分析上传文件并生成规则。</p>
              </div>
            )
          )}
        </div>

        <div className="flex justify-end gap-3 border-t border-gray-100 px-6 py-4">
          <button onClick={onCancel} className="rounded-lg border border-gray-300 px-4 py-2 text-gray-700 hover:bg-gray-50">
            取消
          </button>
          {aiRule && (
            <>
              <button
                onClick={onTest}
                disabled={!!aiConfigError}
                className="flex items-center gap-2 rounded-lg bg-blue-50 px-4 py-2 text-blue-600 hover:bg-blue-100 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <Eye className="h-4 w-4" />
                试解析
              </button>
              <button
                onClick={onSave}
                disabled={!!aiConfigError}
                className="rounded-lg bg-gray-100 px-4 py-2 text-gray-700 hover:bg-gray-200 disabled:cursor-not-allowed disabled:opacity-50"
              >
                保存规则
              </button>
              <button
                onClick={onApply}
                disabled={!!aiConfigError}
                className="jt-btn-primary px-4 py-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                使用此规则解析
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

function EditRuleModal({
  rule,
  onChange,
  onCancel,
  onTest,
  onSave,
}: {
  rule: ParsingRule
  onChange: (rule: ParsingRule) => void
  onCancel: () => void
  onTest: () => void
  onSave: () => void
}) {
  const [configError, setConfigError] = useState<string | null>(null)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-3 md:p-6">
      <div className="flex max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-gray-100 px-6 py-4">
          <h3 className="text-xl font-bold text-[#1d2129]">编辑解析规则</h3>
          <button onClick={onCancel} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
            <X className="h-5 w-5" />
          </button>
        </div>
        <div className="flex-1 space-y-4 overflow-y-auto px-6 py-5">
          <div className="grid gap-4 md:grid-cols-2">
            <label className="text-sm text-gray-700">
              规则名称
              <input
                type="text"
                value={rule.name}
                onChange={(event) => onChange({ ...rule, name: event.target.value })}
                className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
              />
            </label>
            <label className="text-sm text-gray-700">
              文件类型
              <select
                value={rule.file_type}
                onChange={(event) => onChange({ ...rule, file_type: event.target.value as ParsingRule['file_type'] })}
                className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
              >
                {Object.entries(FILE_TYPE_LABELS).map(([value, label]) => (
                  <option key={value} value={value}>{label}</option>
                ))}
              </select>
            </label>
          </div>
          <label className="block text-sm text-gray-700">
            描述
            <textarea
              value={rule.description || ''}
              onChange={(event) => onChange({ ...rule, description: event.target.value })}
              rows={2}
              className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
            />
          </label>
          <label className="block text-sm text-gray-700">
            结构类型
            <select
              value={rule.structure_type}
              onChange={(event) => onChange({ ...rule, structure_type: event.target.value as ParsingRule['structure_type'] })}
              className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-[#0fc6c2]"
            >
              {Object.entries(STRUCTURE_TYPE_LABELS).map(([value, label]) => (
                <option key={value} value={value}>{label}</option>
              ))}
            </select>
          </label>
          <RuleConfigForm
            rule={rule}
            onChange={(config) => onChange({ ...rule, config: normalizeRuleConfig(config) })}
            onValidityChange={(valid, message) => setConfigError(valid ? null : (message || '规则配置格式不正确'))}
          />
        </div>
        <div className="flex justify-end gap-3 border-t border-gray-100 px-6 py-4">
          <button onClick={onCancel} className="rounded-lg border border-gray-300 px-4 py-2 text-gray-700 hover:bg-gray-50">
            取消
          </button>
          <button
            onClick={onTest}
            disabled={!!configError}
            className="flex items-center gap-2 rounded-lg bg-blue-50 px-4 py-2 text-blue-600 hover:bg-blue-100 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Eye className="h-4 w-4" />
            试解析
          </button>
          <button
            onClick={onSave}
            disabled={!!configError || !rule.name.trim()}
            className="jt-btn-primary px-4 py-2 disabled:cursor-not-allowed disabled:opacity-50"
          >
            保存修改
          </button>
        </div>
      </div>
    </div>
  )
}

function PreviewModal({
  previewing,
  previewError,
  previewData,
  onClose,
}: {
  previewing: boolean
  previewError: string | null
  previewData: ShipmentData[]
  onClose: () => void
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-3 md:p-6">
      <div className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-xl bg-white p-6">
        <div className="mb-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Eye className="h-5 w-5 text-blue-600" />
            <h3 className="text-xl font-bold text-[#1d2129]">试解析预览</h3>
          </div>
          <button onClick={onClose} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto">
          {previewing && (
            <div className="flex items-center justify-center py-12">
              <RefreshCw className="h-8 w-8 animate-spin text-[#0fc6c2]" />
              <span className="ml-3 text-gray-600">正在解析...</span>
            </div>
          )}

          {previewError && !previewing && (
            <div className="rounded-xl border border-red-200 bg-red-50 p-4">
              <div className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-red-500" />
                <span className="font-medium text-red-700">{previewError}</span>
              </div>
            </div>
          )}

          {previewData.length > 0 && !previewing && (
            <div>
              <div className="mb-3 flex items-center gap-2 rounded-lg bg-blue-50 p-3">
                <Info className="h-4 w-4 text-blue-600" />
                <span className="text-sm text-blue-700">
                  解析成功！共 {previewData.length} 条记录{previewData.length === 20 && '（仅显示前 20 条）'}
                </span>
              </div>
              <div className="overflow-x-auto rounded-lg border border-gray-200">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-3 py-2 text-left text-xs font-medium uppercase tracking-wider text-gray-500">#</th>
                      {Object.keys(previewData[0] || {})
                        .filter(key => key !== 'id' && key !== 'created_at' && previewData[0]?.[key as keyof ShipmentData] !== undefined)
                        .map(key => (
                          <th key={key} className="whitespace-nowrap px-3 py-2 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                            {FIELD_DISPLAY_NAMES[key] || key}
                          </th>
                        ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-200 bg-white">
                    {previewData.map((row, index) => (
                      <tr key={index} className="hover:bg-gray-50">
                        <td className="px-3 py-2 text-sm text-gray-500">{index + 1}</td>
                        {Object.keys(row)
                          .filter(key => key !== 'id' && key !== 'created_at')
                          .map(key => (
                            <td
                              key={key}
                              className="max-w-[200px] truncate whitespace-nowrap px-3 py-2 text-sm text-gray-700"
                              title={String(row[key as keyof ShipmentData] ?? '')}
                            >
                              {String(row[key as keyof ShipmentData] ?? '-')}
                            </td>
                          ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
